### ISSUE TITLE
Can't Log into Admin side. 

### ISSUE THREAD

**Issue by ajmyers01** [mageinferno/magento2-docker-compose#10]
I've built the containers and have successfully loaded up my site, however when I got to log in to the admin side, the username magento2 and password magento2 don't seem to do anything. 

No error message is thrown i'm just redirected to the admin sign in page again. 

I've confirmed the Admin user exists: 
![](https://dl.dropboxusercontent.com/spa/l2plmwrbl136qhn/hxoml7z_.png)

My code is hosted at this repo. https://github.com/ajmyers01/magento_docker 

I"m unsure if maybe the DB container isn't hooked up to the app correctly or something.

Thanks for your help and the great repo !

**Comment by ajmyers01** [comment]
Update: Regular customer accounts also don't work.

**Comment by markoshust** [comment]
So it sounds as if cookies are not being properly set, or the domain/virtualhost isn't properly set.

What is this Dockerfile for? https://github.com/ajmyers01/magento_docker/blob/master/Dockerfile

It looks like you are using outdated images in your docker-compose.yml file. Check out https://github.com/mageinferno/magento2-docker-compose, note the specific version numbers. This is the recommended practice now. So for example image `mageinferno/magento2-nginx:1.9` should be changed to `mageinferno/magento2-nginx:1.9.9-2`, `mageinferno/magento2-php:5.6-fpm` changed to `mageinferno/magento2-php:5.6.17-fpm-1`, etc.

Try reinstalling with the newest docker compose file at https://github.com/mageinferno/magento2-docker-compose. For now I'll close this ticket, as I think the outdated images are causing the issues.
