### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by kubaceg** [mageinferno/magento2-docker-compose#11]
How I can run M2 tests on this docker? There is no php5-cli package installed

**Comment by markoshust** [comment]
No clue! :stuck_out_tongue_closed_eyes: 

I haven't worked out build/production/deploy flows yet. I think we need diagrams here on how this would all work, in tandem with the already-built images.

**Comment by kubaceg** [comment]
php5-cli is necessary not only for tests but for m2 tools too, so mayme You should start with install this package on php image :)

**Comment by markoshust** [comment]
This should be already installed with php-fpm.

```
root@e3677ad1434d:/# which php
/usr/local/bin/php
root@e3677ad1434d:/# php -v
PHP 7.0.4 (cli) (built: Mar  9 2016 02:18:50) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

I'm going to close out this ticket, because it appears this is all you need for everything, unless you can provide an example that isn't working.
