### ISSUE TITLE
Which container has cron running? (indexes not being updated)

### ISSUE THREAD

**Issue by alankent** [mageinferno/magento2-docker-compose#12]
Which container runs the cron job? Without cron jobs running you cannot do updates, and indexes will not necessarily be synced. I got the warning coming up about indexes being out of date, and check that cron jobs are running. (There are 3 of them.)

**Comment by markoshust** [comment]
The cronjobs are running, they are setup in php image, and are executed as www-user

The PHP Dockerfile runs ./bin/start https://github.com/mageinferno/docker-magento2-php/blob/master/bin/start
This kicks off setup-config https://github.com/mageinferno/docker-magento2-php/blob/master/bin/setup-config
There, you can see what I'm doing with cronjob.

I believe after initial install, you should trigger a reindex to kick things off. Perhaps this is a bug with M2 + sample data. I had this in old setup files, but removed it so setup completes quicker.
`docker exec -it CONTAINER_ID ./bin/magento indexer:reindex`

**Comment by kusmierz** [comment]
OR as docker-composer 1.7.x, you could run:

```
docker-compose exec phpfpm ./bin/magento indexer:reindex
```
