### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by SantoDE** [mageinferno/magento2-docker-compose#15]
Hey there,

thanks a lot for your awesome image. However, I'm struggling to get this up and running.  I read about the magento file permission problem and that your script fixes them. However, it's not working on my machine here. I'm also using dinghy as you guys do. The setup script is not able to chown the files

> chown: changing ownership of '/srv/www/vendor/magento/magento2-base/dev/tests/functional/tests/app/Magento/Backup/Test/Page/Adminhtml': Operation not permitted
chown: changing ownership of '/srv/www/vendor/magento/magento2-base/dev/tests/functional/tests/app/Magento/Backup/Test/Page': Operation not permitted
chown: changing ownership of '/srv/www/vendor/magento/magento2-base/dev/tests/functional/tests/app/Magento/Backup/Test/TestCase/NavigateMenuTest.xml': Operation not permitted
chown: changing ownership of '/srv/www/vendor/magento/magento2-base/dev/tests/functional/tests/app/Magento/Backup/Test/TestCase': Operation not permitted

Any ideas? :) Thanks!

**Comment by SantoDE** [comment]
Okay, after reading a lot up (especially from here: https://github.com/mageinferno/magento2-docker-compose/issues/5) and about dinghy, I know about the chown problem.

However, writing to /var/sessions is still not possible for me yet. I still encounter the issues you had in issue 5. Anything I'm missing?

**Comment by markoshust** [comment]
Are you using the most recent images as in https://mageinferno.com/blog/magento-2-speed-security-permissions-docker ?

This should also all be fixed, as 2416 (magento 2.0.6) has updates to not include permission setting at the application level.

**Comment by SantoDE** [comment]
Yeah, I just updated to 2416 (2.0.6) and I'm using all recent images. That's why I'm really confused. Any special config needed for dinghy or something?

**Comment by markoshust** [comment]
ah -- to use with dinghy, you need to set it up just like any other dinghy project, by creating docker images specifically from the bast images to get dinghy to mount with the correct file permissions.

for example, to build php image, create the Dockerfile:
```
FROM mageinferno/magento2-php:7.0.5-fpm-0
RUN usermod -u 501 www-data
```

then: `docker build -t . my-php`. 

l'm going to close this ticket, as I believe this is just in the implementation details of dinghy + docker.

**Comment by SantoDE** [comment]
Thanks a lot @markoshust . I totaly missed that point!
