### ISSUE TITLE
Create documentation for ./bin/magento exec

### ISSUE THREAD

**Issue by markoshust** [mageinferno/magento2-docker-compose#17]
per https://github.com/mageinferno/docker-magento2-php/issues/15

**Comment by nileshadiyecha** [comment]
Thanks for your guidance.

So first I would need execute below docker-compose command to launch the PHPFPM container.
- " docker run --rm --name phpfpm -v /var/www/html/:/var/www/webroot/site/ mageinferno/magento2-php:7.0.5-fpm-0 ./bin/magento "

Then for each bin/magento command execution - I would need to use below command.
- " docker-compose exec phpfpm ./bin/magento cache:clean / cron:run / sampledata:install "

Is this the right way?

**Comment by nileshadiyecha** [comment]
My magento2 application root @ hostmachine is "/var/www/html/" & for PHPFPM container it is "/var/www/webroot/site/" .

**Comment by markoshust** [comment]
You want to boot up docker compose using the instructions at https://mageinferno.com/blog/magento-2-speed-security-permissions-docker

**Comment by nileshadiyecha** [comment]
While I run the below command I am getting the error message.

**Command:**
docker run --rm --name phpfpm -v /var/www/html/controls/app/webroot/:/srv/www/ mageinferno/magento2-php:7.0.6-fpm-0 ./bin/magento

**Error Message:**
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 20480 bytes) in /srv/www/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 24

Can you please guide me on this.

**Comment by markoshust** [comment]
@nileshadiyecha it's possible it's timing out from not finding mysql linked. why are you running one-off containers for this? it is much easier to use docker-compose. follow the link above to find out how to do this, it's near the end of the article.

**Comment by nileshadiyecha** [comment]
@markoshust - I am getting below error message while execution " docker-compose exec phpfpm ./bin/magento cache:clean

**Error Message:**
[InvalidArgumentException]
There are no commands defined in the "cache" namespace.

**Comment by lsv** [comment]
The working way is this `docker exec xxxx_phpfpm_1 ./bin/magento`
You can find your phpfpm name with `docker ps`

Fx

```bash
docker exec magento2dev_phpfpm_1 ./bin/magento info:adminuri
```

Gives me the admin url

For easier access create I create a magento.sh in my root, with the content of

```bash
docker exec magento2dev_phpfpm_1 ./bin/magento
```

So I can now just run `magento info:adminuri`

**Comment by nileshadiyecha** [comment]
yes, it is working fine.
Thanks a lot for your guidance.

**Comment by markoshust** [comment]
Added lot of this to readme, thanks guys

**Comment by lsv** [comment]
Also if you want to connect to a container fx to do some bash stuff

```sh
docker exec -t -i <container> /bin/bash
```

Though with those images used in this docker-compose you need to set TERM env variable before you can fx connect to mysql

So first connect to the mysql container

```sh
docker exec -t -i magento2dev_db_1 /bin/bash
$ echo "export TERM=xterm" >> ~/.bashrc
$ exit
```

Now relogin and you can now login into mysql

```sh
docker exec -t -i magento2dev_db_1 /bin/bash
$ mysql -u magento2 -pmagento2
```
