### ISSUE TITLE
Error during setup process

### ISSUE THREAD

**Issue by katat** [mageinferno/magento2-docker-compose#18]
I copied the docker-compose.yml from this repo and run the following command to setup m2:

`docker-compose run --rm setup`

It responses:

 `SQLSTATE[HY000] [2002] No route to host`. 

` [InvalidArgumentException]`
`Parameter validation failed`

Any ideas of what could be the causes?

Thanks

**Comment by navarr** [comment]
I'm having a similar issue where there is "No route to host" attempting to install Magento2 (manually)

**Comment by markoshust** [comment]
Is this still an issue? I'm wondering if a new version of Docker messed something up. Sometimes, it took 3-4 seconds for the MySQL container to initially boot, and running the command a subsequent time (when the container has been primed) fixes that issue.

**Comment by markoshust** [comment]
Closing from inactivity

**Comment by MasterCATZ** [comment]
have same issue 

what was solution ?
