### ISSUE TITLE
Cant start setup container

### ISSUE THREAD

**Issue by lsv** [mageinferno/magento2-docker-compose#19]
Something happended pretty recently - Now I can not bootup the setup anymore

```
git clone https://github.com/mageinferno/magento2-docker-compose.git
docker-compose run --rm setup

Starting magento2dockercompose_appdata_1
Starting magento2dockercompose_dbdata_1
Starting magento2dockercompose_db_1
ERROR: Cannot link to a non running container: /magento2dockercompose_db_1 AS /magento2dockercompose_setup_run_9/db
```

**Comment by lsv** [comment]
You actually need to do a `docker-composer up -d` before running the `docker-compose run --rm setup`

**Comment by markoshust** [comment]
@lsv no you don't, just `docker-compose run --rm setup`. There are times where the db instantiation takes a few seconds... in that case, just run the line again, and it should setup. If that doesn't solve the issue, please let me know.
