### ISSUE TITLE
Issue on index.php

### ISSUE THREAD

**Issue by itwars** [mageinferno/magento2-docker-compose#2]
Hi,

I got an issue when browsing the index page : 

![magento2](https://cloud.githubusercontent.com/assets/353918/12034632/045f8656-ae34-11e5-9e07-240c8a200f60.jpg)

Fatal error: Uncaught Error: Call to a member function getValue() on boolean in /src/vendor/magento/module-catalog/Pricing/Render/FinalPriceBox.php:101 Stack trace: #0 /src/vendor/magento/module-catalog/view/base/templates/product/price/final_price.phtml(24): Magento\Catalog\Pricing\Render\FinalPriceBox->hasSpecialPrice() #1 /src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/src/vendor/mag...') #2 /src/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Pricing\Render\FinalPriceBox), '/src/vendor/mag...', Array) #3 /src/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/src/vendor/mag...') #4 /src/vendor/magento/framework/Pricing/Render/PriceBox.php(65): Magento\Framework\View\Element\Template->_toHtml() #5 /src/vendor/magento/module-catalog/Pricing/Render/FinalPriceBox.php(31): Magento\Framework\Pricing\Render\PriceBox->_toHtml() #6 /src/vendor/magento/framework/Vi in /src/vendor/magento/module-catalog/Pricing/Render/FinalPriceBox.php on line 101

**Comment by markoshust** [comment]
What `MAGE_MODE` are you running, and are you using the most recent images? (mageinferno/php:7.0.1-fpm-2)

**Comment by itwars** [comment]
APP_MAGE_MODE=production + git pull then a complete rebuild ...

**Comment by markoshust** [comment]
I'm not sure how git is coming into play here, however you need to rebuild
static assets if you are setting APP_MAGE_MODE. This is most likely the
issue.

**Comment by itwars** [comment]
*git pull* is to update files from your git repo. 
Anyway, I've :
- removed all docker images+containers,
- removed composer cache,
- start the all process by starting : docker-compose up

During the build process I got this error : 
> setup_1   | phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
> setup_1   | symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
> setup_1   | sjparkinson/static-review suggests installing sensiolabs/security-checker (Required for ComposerSecurityReview.)
> setup_1   | lusitanian/oauth suggests installing symfony/http-foundation (Allows using the Symfony Session storage backend.)
> setup_1   | lusitanian/oauth suggests installing predis/predis (Allows using the Redis storage backend.)
> setup_1   | Writing lock file
> setup_1   | Generating autoload files
> setup_1   | Installing composer dependencies...
> setup_1   | ./composer.json has been updated
> setup_1   | Loading composer repositories with package information
> setup_1   |
> setup_1   |
> setup_1   |
> setup_1   |   [Composer\Downloader\TransportException]
> setup_1   |   The 'https://repo.magento.com/packages.json' URL required authentication.
> setup_1   |   You must be using the interactive console to authenticate
> setup_1   |
> setup_1   |
> setup_1   |
> setup_1   | There is an error during sample data deployment.
> setup_1   | require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]
> setup_1   |
> setup_1   |
> setup_1   | Ignore the above error (bug in Magento), fixing with 'composer update'...
> setup_1   | Loading composer repositories with package information
> setup_1   | Updating dependencies (including require-dev)
> setup_1   |   - Installing magento/module-catalog-sample-data (100.0.2)
> setup_1   |     Downloading: 100%

**Comment by markoshust** [comment]
This is an error with Magento -- however it should be a non issue. I placed a note in the installer after that error to ignore it:

```
setup_1 | Ignore the above error (bug in Magento), fixing with 'composer update'...
```

Everything should continue installing and run with no issue.

**Comment by markoshust** [comment]
FYI I just merged this PR to rebuild static assets on an install -- this could perhaps fix any issues you may have been having. https://github.com/mageinferno/docker-magento2-php/pull/5
