### ISSUE TITLE
app/code

### ISSUE THREAD

**Issue by tomhoad** [mageinferno/magento2-docker-compose#20]
Where does the `app/code` directory come from in the readme? This isn't a standard Magento directory?

**Comment by markoshust** [comment]
I'm closing because this is a question, not an issue. But look at https://github.com/mageinferno/magento2-docker-compose/blob/master/docker-compose.yml -- it's mounted, if you want, at runtime as a volume.

**Comment by A111ex** [comment]
link does not work

**Comment by markshust** [comment]
@A111ex the current link is https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml
