### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by ClaudiuCreanga** [mageinferno/magento2-docker-compose#22]
I get no /srv/www/ folder in my container. Tried on ubuntu and mac. 

Pulled the images, copied this docker compose file and followed the instructions from the readme. 

When running docker cp afbc12492752:/srv/www ./ I get no www folder.

**Comment by markoshust** [comment]
I'm closing this as it's more of a question than a bug report. I'd recommend asking your question at stackoverflow.com
