### ISSUE TITLE
File changes dose not sync with appdata container

### ISSUE THREAD

**Issue by smmuthu** [mageinferno/magento2-docker-compose#23]
Hi, 

I have changed the appdata volume's mount point to - ./www:/srv/www and restart the containers but my changes on my local folder ./www was not sync with appdata volume. Can any help me to resolve this.

Thanks
Mari S

**Comment by markoshust** [comment]
You'll need to create a ticket on stackoverflow.com or similar -- I'm only taking reported bugs/issues right now, not tech support help

**Comment by smmuthu** [comment]
Thanks Mark.
