### ISSUE TITLE
Magento Admin Credentials

### ISSUE THREAD

**Issue by hickscorp** [mageinferno/magento2-docker-compose#24]
Once installed, I'm trying to get a way to authenticate as an admin into the fresh instance. To get the admin URL to use, I issued:

`docker exec -it magento_phpfpm_1 ./bin/magento info:adminuri`

It gave me the URL I needed to use. Now from that URL, what's the admin username / password?

**Comment by grantkemp** [comment]
+1 for me.

**Comment by hickscorp** [comment]
@grantkemp The solution follows, it might be useful for you.

I realized that after bringing the containers up, one of them is a fully functional instance. Using the magento cli as usual would work:

```
docker exec -it magento_phpfpm_1 ./bin/magento admin:user:create \
  --admin-firstname John \
  --admin-lastname DOE \
  --admin-email johnd@mor.org \
  --admin-user admin_username \
  --admin-password password
```

**Comment by markoshust** [comment]
They are set in your docker-compose :)
https://github.com/mageinferno/magento2-docker-compose/blob/master/docker-compose.yml#L61

**Comment by grantkemp** [comment]
I used Kitmatic- and it doesn't seem to work - I will try it out on command line.  But we should make sure Kitematic users are supported as thats the current GUI recommended by Docker toolbox

**Comment by markoshust** [comment]
What isn't set in Kitematic? These are standard docker-compose files.

**Comment by grantkemp** [comment]
When you run kitematic you get this screen - and opening the weblink doesn't work 

![image](https://cloud.githubusercontent.com/assets/751115/17482848/7fb2bd36-5d7b-11e6-984f-9de57aee51ad.png)

it just generates this page: 
![image](https://cloud.githubusercontent.com/assets/751115/17482896/a48a8df0-5d7b-11e6-84a0-b086c8a15077.png)

**Comment by markoshust** [comment]
This error doesn't seem to be related to admin credentials at all... please open a new ticket with full explanation and how to reproduce

**Comment by grantkemp** [comment]
I thought the issue was caused in Kitematic becuase you aren't given the opp to enter them.  
Will leave it for now and try again in a few months with others who are more familiar with Docker and kitematic have had a look.

**Comment by markoshust** [comment]
Even if you are using something like Kitematic, you need to execute the setup container to setup Magento. I'm not familiar how to do this with Kitematic, as I really only use the CLI.

**Comment by grantkemp** [comment]
@markoshust  yep - I gathered that from your response.  I think this looks like the relevant issue. If it is, maybe you can give them a more constructive suggestion than I could?

https://github.com/docker/kitematic/issues/550

**Comment by markoshust** [comment]
Unfortunately I'm completely ignorant of GUI-based docker tools.... and my Magento 2 involvement has dramatically diminished. Hope the community can respond here!

**Comment by grantkemp** [comment]
Moved to a new issue, hopefully someone can respond.  Cheers @markoshust
