### ISSUE TITLE
Host not found?

### ISSUE THREAD

**Issue by grantkemp** [mageinferno/magento2-docker-compose#25]
Just tried to spin this up and got this error: 

>  1#1: host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2
> nginx: [emerg] host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2

Any Idea how to resolve?

**Comment by markoshust** [comment]
Can you ensure you are using all of the most recent docker image tags? We haven't used `php-fpm` for some time. It was renamed a while ago to `phpfpm` to avoid issues with dashes in docker-compose files.

See here for most recent docker compose file and tags: https://github.com/mageinferno/magento2-docker-compose/blob/master/docker-compose.yml#L21

**Comment by markoshust** [comment]
Closing due to this appearing to be a user config/docker-compose issue
