### ISSUE TITLE
Kitematic Not working with this.... any ideas?

### ISSUE THREAD

**Issue by grantkemp** [mageinferno/magento2-docker-compose#26]
When you run kitematic you get this screen - and opening the weblink doesn't work 

![image](https://cloud.githubusercontent.com/assets/751115/17482848/7fb2bd36-5d7b-11e6-984f-9de57aee51ad.png)

it just generates this page: 
![image](https://cloud.githubusercontent.com/assets/751115/17482896/a48a8df0-5d7b-11e6-84a0-b086c8a15077.png)

**Comment by markoshust** [comment]
did you find a solution?
