### ISSUE TITLE
Kitematic Not working with this.... any ideas?

### ISSUE THREAD

**Issue by grantkemp** [mageinferno/magento2-docker-compose#27]
When you run kitematic you get this screen - and opening the weblink doesn't work 

![image](https://cloud.githubusercontent.com/assets/751115/17482848/7fb2bd36-5d7b-11e6-984f-9de57aee51ad.png)

it just generates this page: 
![image](https://cloud.githubusercontent.com/assets/751115/17482896/a48a8df0-5d7b-11e6-84a0-b086c8a15077.png)

This may be a relevant issue - however it might be down to someone in the community who knows about Kitematic and Docker more that can make a relevant suggestion to help this project support Kitematic: 

docker/kitematic#550

**Comment by markoshust** [comment]
Since this isn't a bug report but rather a support request, please post your question to stackoverflow instead http://stackoverflow.com/questions/tagged/docker

This repo just supports CLI, though other methods should work just fine.
