### ISSUE TITLE
How to access Magento Connect?

### ISSUE THREAD

**Issue by hickscorp** [mageinferno/magento2-docker-compose#28]
Hello,

Again, newbee with Magento here. Basically, after installing Magento using the docker-compose playbook, we would like to install an extension, but the Magento Connect link as per mentioned from their docs doesn't exist in the System tab of the admin panel.

I've tried contacting Magento about it, but they seem to think the best place for the issue is right here (See [this thread](https://github.com/magento/magento2/issues/6102#issuecomment-238871932)).

Any clue please?

**Comment by markoshust** [comment]
This isn't the place for questions (only bugs/issues). Please use stackoverflow.com for questions, keeps the issues neat & tidy

**Comment by hickscorp** [comment]
@markoshust This really is raised by an issue with some of the directives from the README file. We basically tried following the `auth.json` directives along with changing the `M2SETUP_USE_ARCHIVE` to `false` but either combination of those things just makes the setup container fails. It's probably us being too much new to this whole Magento thing to understand why it fails really.

Could someone please ellaborate on the order of those steps maybe?
