### ISSUE TITLE
Can't shared folder between Host and Container

### ISSUE THREAD

**Issue by damianfabian** [mageinferno/magento2-docker-compose#29]
Hello, 

I'm trying to follow all the steps to create a dev environment with Docker, but when I try to shared folder to start editing something in Magento, I could not see any file into the container. I'm using Windows 10, my Docker version is 1.12.0-rc4-beta20(build 5579). 

The folders seems to be mounted but when I try to see the files, the folders are empty. 

Any idea what can I do?

**Comment by markoshust** [comment]
Since this is a support issue, and not bug report, I'd recommend posting your question to stackoverflow http://stackoverflow.com/questions/tagged/docker
