### ISSUE TITLE
Problem Setting Up

### ISSUE THREAD

**Issue by anantab** [mageinferno/magento2-docker-compose#32]
Fixed by changing 
  - ~/.composer:/var/www/.composer to
  - ~/.composer:/srv/www/.composer
in docker-compose.yml

=================

Hi,
After following all steps and running 
docker-compose run --rm setup
I get  : 

Starting mangeto2_appdata_1
Starting mangeto2_dbdata_1
Creating mangeto2_db_1
Initializing setup...
Installing magento/project-community-edition (2.1.0)

  [InvalidArgumentException]
  Project directory ./ is not empty.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

chmod: cannot access './bin/magento': No such file or directory
Running Magento 2 setup script...
Could not open input file: ./bin/magento
The setup script has completed execution.

**Comment by markoshust** [comment]
Thanks for that! Minor typo in the commented out line in the docker compose. All fixed.
