### ISSUE TITLE
Running Magento 2 setup script... No route to host

### ISSUE THREAD

**Issue by MasterCATZ** [mageinferno/magento2-docker-compose#33]
docker-compose run --rm setup

Running Magento 2 setup script...
SQLSTATE[HY000] [2002] No route to host

                               
  [InvalidArgumentException]   
  Parameter validation failed  
                               

docker-compose up -d app

Localhost:8000

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\App\Config\Scope\ReaderPoolInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73 Stack trace: #0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'readerPool', 'Magento\\Framewo...') #3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array) #4 /var/www/html/vendor/magento/framework/Object in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73

CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                       PORTS                                              NAMES                                  SIZE
f28e55bff353        mageinferno/magento2-nginx:1.11-0     "/usr/local/bin/start"   18 minutes ago      Up 18 minutes                443/tcp, 0.0.0.0:8000->80/tcp                      magento2dockercompose_app_1            4.097 kB (virtual 181.4 MB)
e64e30f51802        mageinferno/magento2-php:7.0-fpm-0    "/usr/local/bin/start"   18 minutes ago      Up 18 minutes                9000/tcp                                           magento2dockercompose_phpfpm_1         529 B (virtual 593.6 MB)
d940031ebaab        redis:latest                          "docker-entrypoint.sh"   45 minutes ago      Up 45 minutes                6

**Comment by markoshust** [comment]
Sounds like a possible issue with Docker. What version of Docker are you running, and what operating system?

**Comment by MasterCATZ** [comment]
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial


Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

**Comment by markoshust** [comment]
Can you post your docker-compose file here also?

**Comment by MasterCATZ** [comment]
just the default file 

`# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 5.0.0

app:
  image: mageinferno/magento2-nginx:1.11-0
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  ports:
    - 8000:80

appdata:
  image: tianon/true
  volumes:
    - /var/www/html
#    - ~/.composer:/var/www/.composer
#    - ./html/app/code:/var/www/html/app/code
#    - ./html/app/design:/var/www/html/app/design

phpfpm:
  image: mageinferno/magento2-php:7.0-fpm-0
  links:
    - db
  volumes_from:
    - appdata

db:
  image: percona:5.7
  volumes_from:
    - dbdata
  ports:
    - 8001:3306
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.0-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://m2.localhost:8000/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_VERSION=2.1.2
    - M2SETUP_USE_SAMPLE_DATA=true
    - M2SETUP_USE_ARCHIVE=true`

**Comment by markoshust** [comment]
What happens when you run `docker-compose run --rm setup` twice in a row?

I'm unable to replicate this :(

**Comment by MasterCATZ** [comment]
deleted and re git cloned 

worked first time 

unsure what went wrong last time 

tried all sorts of docker-compose  variations last time 

maybe something related to the other Magento containers I had pulled from docker hub 10 weeks ago that I had removed this morning

**Comment by markoshust** [comment]
K glad you got it working
