### ISSUE TITLE
php memory issue 'Allowed memory size of 2097152 bytes exhausted'

### ISSUE THREAD

**Issue by Anton-Latukha** [mageinferno/magento2-docker-compose#34]
Using current version docker-compose file.
On fresh (volumes was deleted) install.

With diff:
```
$ diff ./docker-compose.yml ./docker-compose2.ym
12c12
<     - 80:80
---
>     - 8000:80
17c17
<     - mageAD:/var/www/html
---
>     - /var/www/html
44c44
<     - mageDB:/var/lib/mysql
---
>     - /var/lib/mysql
58c58
<     - M2SETUP_BASE_URL=http://m2.localhost:80/
---
>     - M2SETUP_BASE_URL=http://m2.localhost:8000/
61c61
<     - M2SETUP_ADMIN_EMAIL=my_mail@email.mail
---
>     - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
```

Receive:
`phpfpm_1   | Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 12288 bytes) in /var/www/html/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 8
`

Main page loads. But not admin uri (used proper uri `docker exec magento2_phpfpm_1 magento info:adminuri`)

```
phpfpm_1   | 172.17.0.3 -  11/Nov/2016:12:57:30 +0000 "GET /index.php" 302
app_1      | 172.17.0.1 - - [11/Nov/2016:12:57:30 +0000] "GET /index.php/admin_9gkfm7/admin/index/index/key/f24a62a98b62ea5b1c0038ff548f76859ded621f96fc6590910c9c055d736676/ HTTP/1.1" 302 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36" "-"

```

Reacieving in browser:
```
The m2.localhost page isn’t working

m2.localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

**Comment by markoshust** [comment]
Can you post up your full docker-compose file?

**Comment by Anton-Latukha** [comment]
```
$ cat ./docker-compose.yml 
# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 5.0.0

app:
  image: mageinferno/magento2-nginx:1.11-0
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  ports:
    - 80:80

appdata:
  image: tianon/true
  volumes:
    - mageAD:/var/www/html
#    - ~/.composer:/var/www/.composer
#    - ./html/app/code:/var/www/html/app/code
#    - ./html/app/design:/var/www/html/app/design

phpfpm:
  image: mageinferno/magento2-php:7.0-fpm-0
  links:
    - db
  volumes_from:
    - appdata

db:
  image: percona:5.7
  volumes_from:
    - dbdata
  ports:
    - 8001:3306
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - mageDB:/var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.0-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://m2.localhost:80/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=my_mail@email.mail
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_VERSION=2.1.2
    - M2SETUP_USE_SAMPLE_DATA=false
    - M2SETUP_USE_ARCHIVE=true

```

Additional info:
```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64

```

```
$ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.6
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by markoshust** [comment]
I haven't tested this on a linux distro yet (but will soon).

Any chance the `http://m2.localhost:80/` url is causing the issue? Perhaps try just `http://m2.localhost/` if you are using port 80?

**Comment by Anton-Latukha** [comment]
I considered this be elementary and miniscule changes.
Yes, Ok.
I test it on http://m2.localhost/ and also on all regular settings.
Later today.
And report here.

**Comment by Anton-Latukha** [comment]
I tested.

1. Resolved.
Yes. This is a 

`M2SETUP_BASE_URL=http://m2.localhost:80/`

issue.

Thank you.

P.S
2. Memory limit error in PHP is still present. 
But now I see issues are not interconnected.

> phpfpm_1 | Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 12288 bytes) in /var/www/html/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 8

I can hack memory error with removing limit in php code, but maybe you know and can suggest where to report it. To zend-modulemanager, PHP or I saw discussion of solving massages like this in Docker git?

3. http://m2.localhost:80/ happens.
For me and by default it also must just mean http://m2.localhost/. Can you say where I can report this situation. To nginx or to php or to Magento2.

**Comment by markoshust** [comment]
@Anton-Latukha can you please open a new ticket with detailed info on the memory issue, I don't like colocating multiple issues within one ticket that was opened for something else. Thanks!

**Comment by pravalitera** [comment]
@Anton-Latukha did you ever find why you had the memory limit error ?

**Comment by Anton-Latukha** [comment]
@pravalitera

That was small testing AWS instance. I said to client that we need to get one larger.
Client had bad English, lied to me, was not responsive to do business, and in one moment just stopped responding. So I moved on from him, and never wanted back.

One year past. I don't remember clearly do I got larger instance, do I personally solved that issue, or just moved on.

I want to say, but I can not remember anything strictly.

**Comment by oirad** [comment]
@pravalitera 
I was able to solve this by adding the actual value directly inside the php.ini file and mounting my custom version of it in the container. Apparently the variable `PHP_MEMORY_LIMIT` is not there when running the cron.

**Comment by qurashi123** [comment]
increase your memory_limit to  1G in your php.ini memory_limit 1G.

**Comment by carlos-reynosa** [comment]
I was running into similar memory issues when trying to install a composer package and then updating. It seems that 2G was not enough. I wasn't presented with an error while the composer update command was running so I wasn't why it was just simply failing. I ended up going into the php image by running `./bin/bash `and increasing the php memory to 4G within `/usr/local/etc/php/php.ini `.  That allowed me to properly install a composer module.
