### ISSUE TITLE
Clean install not working

### ISSUE THREAD

**Issue by mgomma** [mageinferno/magento2-docker-compose#38]
Ubuntu 16.04 docker and docker-compose 

mysql and apache2 not installed

**appdata** and **dbdata** always exit and http://m2.localhost:8000/ give not found

appdata setting in .yml

appdata:
  image: tianon/true
  volumes:
#    - /var/www/html
    - ~/.composer:/var/www/.composer
    - ./html/app/code:/home/mhmd/Desktop/docker-projects/magento2-docker-compose/html/app/code
    - ./html/app/design:/home/mhmd/Desktop/docker-projects/magento2-docker-compose/html/app/design

**Comment by markoshust** [comment]
Did you setup DNS for the m2.localhost hostname? This isn't needed for Mac,
but is needed for any other operating system.

**Comment by mgomma** [comment]
It works with me on other machine without doing any other changes as DNS for the m2.localhost hostname?

Where and how to set this, in **hosts** file you mean?

**Comment by markoshust** [comment]
Yes, sounds like you need some entries added to the hosts file (`/etc/hosts`?).
