### ISSUE TITLE
mysite.com

### ISSUE THREAD

**Issue by itwars** [mageinferno/magento2-docker-compose#4]
Hello,

There's something wrong with VIRTUAL_HOST in the **docker-compose.yml**, because even if I change it to localhost or xxxx and rebuild all docker images, the magento web site always refere to http://mysite.com ...

**Comment by markoshust** [comment]
The Magento installation takes in the M2SETUP_BASE_URL param -- was this properly set at installation? If not you'll have to manually update the database config or blow away your containers and start installation over.

```
    - M2SETUP_BASE_URL=http://mysite.com/
```

**Comment by itwars** [comment]
You're rigth! Sorry :)
