### ISSUE TITLE
Configurable git repo

### ISSUE THREAD

**Issue by degaray** [mageinferno/magento2-docker-compose#42]
Can you configure which git repo we want to use? Not all the times you want to run a brand-new copy of Magento2 from scratch. I want to migrate my existing project to Docker and it would be awesome if that could be configured.

**Comment by markoshust** [comment]
You can clone out a git repo to local hard disk and sync up to your Docker repo. There is currently no way to execute a git clone to set this up, however it can be done manually. I don't want to work at this, but will take a PR if you can find a way to do it eloquently :)
