### ISSUE TITLE
sending emails does not work

### ISSUE THREAD

**Issue by michafn** [mageinferno/magento2-docker-compose#43]
Hello, 

first of all: great work! the setup works quite well! However sending emails does not really work. Even after setting up sendmail, which works from the command line (both, in nginx as well as app container) magento does not send any emails. I installed ssmtp to send all emails via an external smtp server, still it doesn't work. I am running out of ideas what to try next. Any ideas? I wonder why sendmail works in the container and properly delivers emails but magento won't...

thanks
 Peter

**Comment by markoshust** [comment]
Email should be configured to send through an external SMTP provider or another cloud-based email service provider such as Mailgun. Sendmail really isn't a scalable option to use within Docker.
