### ISSUE TITLE
m2.localhost:8000 does not work

### ISSUE THREAD

**Issue by samthecarman** [mageinferno/magento2-docker-compose#44]
Thanks for the great article and images. 
I am able to get the site up and running if I use just localhost:8000 in docker-compose.yml. However, if I use m2.localhost:8000 I get a server not found.
Is there an additional configuration step to get m2.localhost:8000 to work?

**Comment by markoshust** [comment]
Be sure to setup local DNS if you are not on macOS Sierra. You'll need to add records to /etc/hosts.

**Comment by samthecarman** [comment]
Thanks Mark. I am on macOS Sierra. Should it work without any records added to /etc/hosts? Additionally, what am I pointing to in my /etc/hosts file? would I point m2.localhost to localhost?

Thanks!

**Comment by markoshust** [comment]
If you are on Sierra you shouldn't need to add any DNS records -- all domains at *.localhost are automatically mapped to 127.0.0.1. You may have to reinstall with the correct domain defined.

**Comment by samthecarman** [comment]
Thanks!
