### ISSUE TITLE
Developer mode

### ISSUE THREAD

**Issue by remklov** [mageinferno/magento2-docker-compose#46]
Hi,

as soon as i activate the developer mode with `docker-compose exec phpfpm ./bin/magento deploy:mode:set developer` , my custom css and scripts.js in not generated in static directory, or at least i get an 404 error. Is it maybe connected to the nginx config?

Regards,
Remklov

**Comment by markoshust** [comment]
With Docker the filesystem is ephemeral, I'm taking a stance on this and saying that you should instead set the developer mode with environment variables, then restart the containers. This will persist better in Docker land.
