### ISSUE TITLE
Run PHP Composer

### ISSUE THREAD

**Issue by julesbravo** [mageinferno/magento2-docker-compose#47]
What is the recommended way to run php composer to install a module?

**Comment by markoshust** [comment]
docker-compose exec phpfpm composer install ...

**Comment by julesbravo** [comment]
@markoshust That doesn't work because this would attempt to run as root and composer will not allow you to run as root.

**Comment by markoshust** [comment]
Hmm, that is actually a good question again. I'll reopen for community feedback.

**Comment by markoshust** [comment]
Perhaps there is a better answer to this, but in the mean time this should work:
`su -c "composer install ..." -s /bin/sh www-data`

**Comment by julesbravo** [comment]
That works for now, I was playing with variations of su yesterday, but couldn't get the right set of options.

Maybe add the ability to easily override the composer.json or a helper script to do things like this?

**Comment by markoshust** [comment]
I'd like a more elegant solution, but you can add this as a bash function in your ~/.bash_profile file or similar. That way you can type something like `dcomposer` instead of `composer` and it'll know it's a docker composer command.

**Comment by julesbravo** [comment]
I did exactly that using "mage-composer" for the time being.

**Comment by markoshust** [comment]
@julesbravo what exact alias did you use? i'd like to close this out and add to readme. cheers

**Comment by julesbravo** [comment]
Mark,

I ended up wiping everything out and going with a vagrant based
implementation for my Magento dev server needs. I no longer have the alias.

**Comment by markoshust** [comment]
closing as non-issue, everything runs as root with docker. will only open back up if there is a related pull request documenting desired functionality and commands to run.
