### ISSUE TITLE
Fatal error: Uncaught Zend_Cache_Exception

### ISSUE THREAD

**Issue by jagwire16** [mageinferno/magento2-docker-compose#5]
After running `docker-compose up`, all of the containers load, but I get a fatal PHP error:

```
Fatal error: Uncaught Zend_Cache_Exception: cache_dir "/src/var/page_cache" is not writable in /src/vendor/magento/zendframework1/library/Zend/Cache.php:209 
Stack trace: 
#0 /src/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/src...')
#1 /src/lib/internal/Cm/Cache/Backend/File.php(82): Zend_Cache_Backend_File->setCacheDir('/src/var/page_c...')
#2 /src/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)
#3 /src/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)
#4 /src/vendor/magento/framework/App/Cache/Frontend/Factory.php(154): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)
#5 /src/vendor/magento/framework/App/Cache/Frontend/Pool.php(67): Magento\Framework\App\Cache\Frontend\Factory->create(Array)
#6 /src/vendor/magento/framework/App/Cache/Frontend/Pool.php(146): Magento\Framework\App\Cach in /src/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
```

Please help!

**Comment by markoshust** [comment]
It seems that I've experienced different permission problems on different systems. This is most likely heavily related to https://github.com/magento/magento2/issues/2412

Since Docker containers are very locked down vs. something like a shared hosting environment, I'm not sure if the normal permission requirements apply. We need to do a bit of research to confirm exactly what we need to do here to 100% resolve this issue so we aren't dealing with it again a month from now.

For now, you can issue a `chmod -R www-data:www-data var pub` and I think it will fix most issues like this that come up.

Some possible steps:
- Get rid of the `magento` user and just use `www-data`. This is the default web user in both the PHP and Nginx containers, so it would be a natural fit. I need a strong reason to keep the `magento` user around, and why. Then, all commands on this container should be executed with the `www-data` user. This would resolve running static compilation as `root`, and then the owner being `root`.
- I believe we need to add in [`USER`](https://docs.docker.com/engine/reference/builder/#user) references into the PHP and Nginx images so that when anything executes on those containers they are properly run.
- We need feedback on https://github.com/magento/magento2/issues/2412 -- perhaps this situation is resolved when `www-data` owns and runs everything.

I'll keep this issue open and hope to get some feedback.

**Comment by HamiltonWang** [comment]
I installed magento2 using command line on CentOS 7 and I encountered the same error. I did set my owner and group to apache and it does't work too.


    Fatal error: Uncaught Zend_Cache_Exception: cache_dir "/var/www/html/magento2/var/page_cache" is not writable in /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/var...') #1 /var/www/html/magento2/lib/internal/Cm/Cache/Backend/File.php(82): Zend_Cache_Backend_File->setCacheDir('/var/www/html/m...') #2 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /var/www/html/magento2/vendor/magento/framework/App/Cache/Frontend/Factory.php(154): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true) #5 /var/www/html/magento2/vendor/magento/framework/App/Cache/Frontend/Pool.php(67): Magento\F in /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Cache.php on line 209

**Comment by markoshust** [comment]
Ok, I put a lot of time & thought into this the last couple weeks. This involved quite a few things:

- I removed the `magento` user completely (in both nginx and php images). I know it's recommended from Magento 2 dev docs (per https://github.com/magento/magento2/issues/2412), but it's causing more issues than what it's worth. I've never heard of the web server user owning documents being a security issue.
- I'm leaving the 775/664 perms because there is nothing but problems running 770/660 perms. I don't know how this can be a security issue in a dedicated hosting environment (which I consider Docker to be). Until there is ever a serious issue with running the owner/perms like this, I'll continue to be extremely opinionated about this and recommending this setup, because it works today, and there are zero problems with this.
- Running the `./bin/magento` command within a Docker container executes the script from the `root` user. This is a problem, because newly generated files were then owned by root. Instead of running the `USER` directive in the Dockerfile, I chose to write a custom shell wrapper for `./bin/magento`, and duplicate the original file out to `./bin/magento-php` -- see https://github.com/mageinferno/docker-magento2-php/blob/master/bin/magento for reference. This wrapper executes this file with the `www-data` user, so any newly generated files are now owned by `www-data`. Boom.
- While I added crontab directives previously, they were never being executed, as `cron` was never started. Oops. I fixed this, and made the crontab entries now owned/ran by `www-data` (https://github.com/mageinferno/docker-magento2-php/blob/master/Dockerfile#L28). 

The docker compose file has been updated to version 3.0.0, which includes the new references to the new images/setup. Please let me know if you experience any user/owner probs with this setup.

Cheers!
Mark

**Comment by clwells** [comment]
Mark,

@miguelbalparda pointed me to https://github.com/magento/magento2/issues/2412 which then led me here.  I'm trying to work on a solution for our clients but I thought I'd comment here and possibly help (or make this more confusing).

>I removed the magento user completely (in both nginx and php images). I know it's recommended from Magento 2 dev docs (per magento/magento2#2412), but it's causing more issues than what it's worth. I've never heard of the web server user owning documents being a security issue.

Assuming a PHP-FPM environment (which I advocate for) the biggest reason to separate webserver user from "normal" user would simply be to isolate one from the other.  Were there a bug in the webserver software you can (and I'd argue should) isolate that bug from allowing your local PHP (and other) files from being altered on the unix permission level.

You can actually run the PHP scripts as 0600 and user owned without the webserver software ever needing to see them.  To extend this you can lock down the config files to be 0600 too which adds an additional layer between a webserver bug and your DB (and other) credentials.

>I'm leaving the 775/664 perms because there are nothing but problems running 770/660 perms. I don't know how this can be a security issue in a dedicated hosting environment (which I consider Docker to be). Until there is ever a serious issue with running the owner/perms like this, I'll continue to be extremely opinionated about this and recommending this setup, because it works today, and there are zero problems with this.

I feel your pain here.  I'm working on some ideas here that (I hope) will allow for a balance of security and usability.  I agree that adding the user to the web group isn't the best solution.. especially if you're in the hosting business.

Chris

**Comment by markoshust** [comment]
Hi @clwells,

Thanks very much for your input. I read your post at https://github.com/magento/magento2/issues/2412#issuecomment-175224546 and this should be called "web & app server permissions for dummies" :)

I'm going to digest that post further and see if I can implement all of the suggestions you pointed out. I completely agree with all of your findings & suggestions, we are absolutely on the same page here. This makes total sense.

**Comment by jagwire16** [comment]
I'm still receiving this error even with the new Docker compose file:

```
<br />
<b>Fatal error</b>:  Uncaught Zend_Cache_Exception: cache_dir &quot;/src/var/page_cache&quot; is not writable in /src/vendor/magento/zendframework1/library/Zend/Cache.php:209
Stack trace:
#0 /src/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir &quot;/src...')
#1 /src/lib/internal/Cm/Cache/Backend/File.php(82): Zend_Cache_Backend_File-&gt;setCacheDir('/src/var/page_c...')
#2 /src/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File-&gt;__construct(Array)
#3 /src/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)
#4 /src/vendor/magento/framework/App/Cache/Frontend/Factory.php(154): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)
#5 /src/vendor/magento/framework/App/Cache/Frontend/Pool.php(67): Magento\Framework\App\Cache\Frontend\Factory-&gt;create(Array)
#6 /src/vendor/magento/framework/App/Cache/Frontend/Pool.php(146): Magento\Framework\App\Cach in <b>/src/vendor/magento/zendframework1/library/Zend/Cache.php</b> on line <b>209</b><br />
```

**Comment by markoshust** [comment]
@jagwire16 when do you receive this error, when installing m2, or when running `app` after install?

**Comment by jagwire16** [comment]
After running the app:
```
docker-compose up -d app
```

**Comment by jdchmiel** [comment]
It seems highly related to this bug - I get:
chown: changing ownership of ' <redacted>': Operation not permitted
for pretty much every file in src.
this occurs when I run:
docker-compose up setup

and when I enter my container and try and run the chown command from the /usr/local/bin/mage-setup command I can reproduce it.  I assume this is related to running on dinghy/OSX.

I was trying to create a workaround by using a dockerfile and doing the commabnd there, but I think I got order of operations mixd up there.

**Comment by markoshust** [comment]
@clwells i just re-read your post at https://github.com/magento/magento2/issues/2412#issuecomment-175224546

would this setup work with php-fpm? at first i thought it would, then i re-read your second sentence in that post, which makes me think it won't work.

**Comment by dimasch** [comment]
Hello, @markoshust 

Thank you for nice work! My workaround for fix this issue:

1) Add run section to php-fpm container:
` RUN usermod -u 502 www-data`

2) Remove unnecessary:
67 line: `chown -R www-data:www-data /src`

Regards,

**Comment by sadhasivam** [comment]
Hello 
i see ```RUN usermod -u 501 www-data```  command in here (https://github.com/mageinferno/docker-magento2-php) readme.  what do we have to use 501 or 502.

**Comment by dimasch** [comment]
Yes, sorry, this case documented in README. Simply rebuild php images with usermod settings.

**Comment by markoshust** [comment]
@sadhasivam @dimasch Yes, it's in the readme. This was in the initial docker images, however i removed it to remain platform agnostic, and leave it up to user to set usermod. Dinghy uses 501, boot2docker uses 1000, etc. Linux doesn't need this set at all.

I'll be adding `user` to Docker builds so everything is jailed to www-user, and not root. I believe this will fix some issues. I will also add in recommendations from magento/magento2#2412 -- this seems to be the valid fix here that will resolve all of these security issues with Magento 2.

Give me a week or so, hope to have something around then. I've been working on another project that is now getting stable, so I'll have some time to circle back around to this pretty soon. Thanks for your patience :)

**Comment by Mattiaz88** [comment]
Hi Mark, I am getting similar problems of @jagwire16 writing into var/generation folder after "docker-compose up setup" command. I am using MacOSX Yosemite, you can find some screnshot below:

![screen shot 2016-03-11 at 17 03 38](https://cloud.githubusercontent.com/assets/1771882/13746700/dd5350c2-e9f4-11e5-8b99-d6886240b6cf.png)
![screen shot 2016-03-11 at 17 03 52](https://cloud.githubusercontent.com/assets/1771882/13746703/dd5ec100-e9f4-11e5-9cd0-54b26d6809de.png)
![screen shot 2016-03-11 at 17 04 00](https://cloud.githubusercontent.com/assets/1771882/13746701/dd56db66-e9f4-11e5-8944-1fe3f09cb9b8.png)
![screen shot 2016-03-11 at 17 04 15](https://cloud.githubusercontent.com/assets/1771882/13746702/dd5ba90c-e9f4-11e5-8cce-ef6a3d26d4cd.png)

**Comment by markoshust** [comment]
FYI I'm working on this right now. I've been very busy on other work and finally back on this, hope to have something out soon.

**Comment by markoshust** [comment]
Ok, I need some help here :) (strapped for time)

I pushed up two new branches for nginx and php-fpm.
https://github.com/mageinferno/docker-magento2-nginx/tree/1.9.12-develop
https://github.com/mageinferno/docker-magento2-php/tree/7.0.4-fpm-0

They are not pushed up to docker hub because they aren't working yet, however I'd love some feedback to find out why. It's almost there.

Changes in these images:
- Added magento user creation to Dockerfile files (random password generation, added to www-data group)
- Changed `php-fpm` to `phpfpm`. This came up a few times for people not putting in dashes in docker-compose, so I just eliminated the dash.
- Updated install files to chown to magento user

It's **almost** there, but I could use some PR's on these branches to get it working fully. I kept the images running as root because it's often needed to go install something (ex. vim, etc), and it was annoying to lock it to a jailed user like magento. I changed nginx and php-fpm to both run under the magento user, so this should resolve perm issues that have been arising.

I'm not full taking @clwells's suggestions in 2412 because they are a bit complex to setup with Docker. However, I used info at http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html and http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html#install-update-depend-user-over -- so this is a much more locked down image, security-wise.

Let me know your thoughts, and please open PR's! I'm managing all of these images myself in my side time, and it's a bit rough :)

Cheers,
Mark

**Comment by markoshust** [comment]
I actually made some ground on this today. In final testing, hope to have something out soon.

**Comment by ITIStudios** [comment]
After all the issues I was having getting magento 2 installed on my nginx server I decided to set up a new apache server on CentOS 7 and now have encounter this error.
I have exhausted all the possibilities I could think of just to get it installed with no success.

Does anybody know what needs to be done to get mag 2 installed on a CentOS 7 server running apache?
Thanks 
Glen

**Comment by sadhasivam** [comment]
@markoshust 
with nginx(1.9.12-develop branch) & 7.0.4.fpm-0  branch images i dont get zendcache exception but i am getting following exception when I access the Magento store.

I am using Mac OSX Yosemite 

```
app_1     | 2016/03/19 04:24:47 [error] 11#11: *5 connect() failed (110: Connection timed out) while connecting to upstream, client: 192.168.99.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://92.242.140.21:9000", host: "mgtostore"
app_1     | 192.168.99.1 - - [19/Mar/2016:04:24:47 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36" "-"
app_1     | 2016/03/19 04:25:05 [error] 11#11: *7 connect() failed (110: Connection timed out) while connecting to upstream, client: 192.168.99.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://92.242.140.21:9000", host: "192.168.99.100"
app_1     | 192.168.99.1 - - [19/Mar/2016:04:25:05 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36" "-"
````

**Comment by shakyShane** [comment]
@markoshust I believe these issues could possibly be solved in the recent 2.0.3 release of M2.

But this creates the question, because your setup script is reliant on either 

1. Your own archives, or
2. The composer installer project thingy

seen https://github.com/mageinferno/docker-magento2-php/blob/master/bin/mage-setup#L9-L18

how can we test everything with a release that is hot-off-press and not made it into the channels above?

**Comment by markoshust** [comment]
@shakyShane i'm really only interested in supporting stable/composer versions. you're free to fork & pull to modify if you need bleeding edge. these images are enough to maintain for the stable versions... 

anyways, i'm waiting until this is confirmed fixed in 2.0.3 by someone else. magento's un-reliance to comment/post or update/inform us about https://github.com/magento/magento2/issues/2412 has made me not want to contribute further to m2. i'm not going to support a project that doesn't care about their users.

**Comment by daim2k5** [comment]
" i'm not going to support a project that doesn't care about their users." so you can delete this project, right? Btw. they care sometimes they need only more time to see or/and learn.

**Comment by markoshust** [comment]
@daim2k5 all i've heard is talk. magento needs to start doing. i'm sick of talk, i've heard this for a long time now. you've had enough time to learn.

i'm not going to delete this project. that would be a disservice to the community. that is a horrible suggestion, and it shows just how disconnected magento inc. is from their dev base.

**Comment by daim2k5** [comment]
@markoshust i'm not magento i only work with magento 1 from the beginning ! and you miss so many points what magento inc. does and that hurts every person that work hard for the current state. I only suggest to delete the project because your written that "i'm not going to support a project that doesn't care about their users.". But now i'm understand that your are only talking and not willing to see other points of views, my fault.

**Comment by jagwire16** [comment]
@daim2k5 This conversation is not fruitful. Please cease and desist.

**Comment by sadhasivam** [comment]
@markoshust Please don't kill the repo. I understand your concern on Magento Inc's commitments and response. probably we can keep some silence and resume back after 2.0.3. in nutshell lots of people would like to see the project going.

in the contribution end, I am not sure I understand the exact issue to help. I am just a naive developer in Magento and naive user in docker. I can help if anything specific you wanted

**Comment by markoshust** [comment]
@sadhasivam I never planned on killing it, nor did I say I wasn't going to maintain it anymore. All I did was mention how I won't support a project that doesn't talk or communicate to their users -- and that is M2. I wouldn't include this repo/project in that discussion -- the feedback and etc. I've had from it has been great.

**Comment by sadhasivam** [comment]
@markoshust great. agreed

**Comment by gabrielqs** [comment]
@markoshust Thanks for your effort on this. It helped me a lot so far.

I have tried the new images, but we're still short on luck. I'm on OS X, using dinghy, configured the DockerFile as described on the readme, but I'm still running on a series of weird behaviours when it comes to permissions.

I have made the new branch images available here in case anyone wants to test them out:

- flowecommerce/magento2-nginx
- flowecommerce/magento2-php

For instance, when the mage-setup script gets to the reindexing part, this pops up:

`Fatal error: Uncaught ErrorException: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/src/var/session/) in /src/vendor/magento/framework/Session/SessionManager.php:139
setup_1   | Stack trace:
setup_1   | #0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'session_write_c...', '/src/vendor/mag...', 139, Array)
setup_1   | #1 /src/vendor/magento/framework/Session/SessionManager.php(139): session_write_close()
setup_1   | #2 [internal function]: Magento\Framework\Session\SessionManager->writeClose()
setup_1   | #3 {main}
setup_1   |   thrown in /src/vendor/magento/framework/Session/SessionManager.php on line 139`

And at the last line - `chown -R www-data:www-data /src` - these pop up:

`setup_1   | chown: changing ownership of '/src/vendor/magento/magento2-base/dev/tests/integration/testsuite/Magento/Email/Model/_files/design/frontend/Magento/default/theme.xml': Operation not permitted
setup_1   | chown: changing ownership of '/src/vendor/magento/magento2-base/dev/tests/integration/testsuite/Magento/Email/Model/_files/design/frontend/Magento/default/web/css/email-3.less': Operation not permitted
setup_1   | chown: changing ownership of '/src/vendor/magento/magento2-base/dev/tests/integration/testsuite/Magento/Email/Model/_files/design/frontend/Magento/default/web/css/email-inline-3.less': Operation not permitted
setup_1   | chown: changing ownership of '/src/vendor/magento/magento2-base/dev/tests/integration/testsuite/Magento/Email/Model/_files/design/frontend/Magento/default/web/css/file-with-error.less': Operation not permitted`

Which is really strange considering this script is being run by root. Maybe something is wrong with my setup? If I attach my terminal to app_1 and try to forcefully set the permissions manually, still no luck.

Finally, when calling the shop from the browser, this pops up:

`Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/src/var/session/) in /src/vendor/magento/module-page-cache/Model/Layout/DepersonalizePlugin.php on line 56 `

Something i didn't understand: what's the reason for the sticky flag at this directory?

`find /src/var/generation -type d -exec chmod g+s {} \;`

I'll keep on trying and will let you know if sort any of it out.

Thanks,
Gabriel

**Comment by gabrielqs** [comment]
So, I actually managed to set the permissions manually:

`root@e5fcc28ad038:/src/var/session# chmod -Rf 777 /src/var/
root@e5fcc28ad038:/src/var/session# ls -Fla
total 0
drwxrwxrwx  6 501 dialout 204 Apr  7 01:40 ./
drwxrwxrwx 16 501 dialout 544 Apr  7 01:58 ../
-rwxrwxrwx  1 501 dialout   0 Apr  7 01:29 sess_30567b1223afb0bbf558beb2f6cd187c*
-rwxrwxrwx  1 501 dialout   0 Apr  7 01:40 sess_3f9c016cc17ee2a48d417d341d39132d*
-rwxrwxrwx  1 501 dialout   0 Apr  7 01:26 sess_d9c6509769e3b8790eb70b00284328fa*
-rwxrwxrwx  1 501 dialout   0 Apr  7 01:40 sess_e9d597d559e9914a3217827953d1c9e8*`

All open, and still receiving this when requesting m2 from the browser:

`Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/src/var/session/) in /src/vendor/magento/module-page-cache/Model/Layout/DepersonalizePlugin.php on line 56`

**Comment by markoshust** [comment]
I believe 2412 issue is in the works, as I've seen some activity there
lately. I really don't want to try to solve this issue until Magento solves
their issues within the software layer.

**Comment by gabrielqs** [comment]
@markoshust Agreed, though I believe the issue I'm looking at now is different from magento/magento2#2412.

The permissions error was happening only with the session folder only. As a temporary fix, i have changed the user running php-fpm to 501 (dinghy stuff), and now all is working. No big worries as i'm still in a dev only environment.

**Comment by markoshust** [comment]
Did you see the heading for OSX / Dinghy at https://github.com/mageinferno/magento2-docker-compose? I wanted to keep this repo platform-agnostic. You'd need to build your own custom images for Dinghy at runtime. If there is a good way to automate this with an `ONBUILD` script or similar at the time the automated builds are published, I'd be all open to that.

**Comment by gabrielqs** [comment]
@markoshust Yes, i've seen that, and i am using the Dinghy specific Dockerfile as well. The thing is that Dinghy/NFS are actually causing 2 issues, as far as i understand:

1. Dinghy seems not to be happy with mage-setup chowning /src to www-data:www-data. Whenever i spin up a new container these errors start popping up, on each and every file on the magento install:
 
 `setup_1   | chown: changing ownership of '/src/vendor/zendframework/zend-view/src/Resolver/TemplateMapResolver.php': Operation not permitted`.
 
 If I fire the same command manually after attaching to the container, the same errors happen. Changing permissions work fine, only changing _ownership_ seems to be a problem.

2. As that fails, the files under /src end up having a dinghy related ownership (501:dialout). That makes it impossible for the php-fpm user defined [here](https://github.com/mageinferno/docker-magento2-php/blob/7.0.4-fpm-0/conf/php-fpm.conf#L14) to write anything... So yeah, maybe a BUILD time script would work. I'll be glad to help you out with that one, but I'm quite new to Docker and unsure on how to proceed. I thought maybe doing something similar to [what you do to the FPM settings](https://github.com/mageinferno/docker-magento2-php/blob/7.0.4-fpm-0/bin/start#L1-L8) would work nice with the php-fpm user as well. What do you think?

Gabriel

**Comment by markoshust** [comment]
Not a problem. I'm going to re-assess all of this as soon as Magento 2.1 is released (should be any day now afaik). I'm hoping they merged in https://github.com/magento/magento2/commit/642127547acbc91f2cb864c3d4880ce4998a9bc4 -- if not I'm going to manually merge this commit in through a startup script or etc. because it needs to happen.

**Comment by markoshust** [comment]
I believe I've made some significant progress today. The changes seem extremely minor, but I think they will correct the permission errors. Basically, I'm foregoing the `magento` user for now, just to get a stable Docker image going without perm errors (on 2.0.4). Everything is owned by the `www-data` user/group, nginx runs as www-data, phpfpm runs as www-data... and everyone should be happy.

The forthcoming images are meant to be treated as a "step 1" in this case, just to get rid of these perm errors so we can start developing right away. The "step 2" of this will be to try to through a new `magento` user in the mix who actually owns the files. I believe this is where the confusion/problems is coming into play now. So, we'll aim to get this stable now with no perm errors, then try to lock everything down with more security later.

I'll release the new images with an `-rc` tags, so we can test these before making them official. Give me a few days to get through tax season here, and I'll have them online.

**Comment by markoshust** [comment]
I just pushed out the new images to rc tags. I'll increment the rc versions as many times as we need to until we can confirm these new images are solid.

Here's a new docker-compose.yml file you can use to test out the new images. They've all been pushed to DockerHub and are ready for testing. You can use the most recent Magento version 2.0.4. All of the other php/nginx/mariadb images were also updated to the most recent versions.

https://gist.github.com/markoshust/72d3eeadfec3746bf434ffbaa79be011

Please give me as much feedback as you can on this, I'll release these as officially tagged versions as soon as I can confirm the security perm probs are gone!

**Comment by sadhasivam** [comment]
@markoshust thanks a lot. . installed the docker-compose.yml in macosx 10.11.4(ElCaption). i see magento console & website without any problem. ZendCache Exception issue is fixed.  But my site is missing products & catalog information. i see empty website.  this problem could be different and likely not related to this ZendCache issue.

**Comment by markoshust** [comment]
Try setting sample data to true in the docker compose. It's an environment
variable you can customize.

**Comment by sadhasivam** [comment]
💯  so far works fine. all good looking. thanks again @markoshust

**Comment by gsc-dev** [comment]
Works well on Windows 10. Thanks @markoshust

**Comment by markoshust** [comment]
Good news on initial feedback!

I pushed out a new version of the docker-compose file to https://gist.github.com/markoshust/72d3eeadfec3746bf434ffbaa79be011

This compose references new images I've just pushed out also. Basically, I moved the www directory from /opt folder to /srv/www (FHS compliant directory http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM), and it can now be set from the environment variables from the Dockerfiles. I moved out the `bin/magento` file to use the one supplied from the magento install, as that could potentially change over time. 

Has anyone found a way to run this with a DNS service for local development on Mac? I've tried my old dinghy setup, however it's failed to resolve with a 503 error. 

This is the simplest way to setup/try this (or to replicate the dinghy issue I'm having). I think I just need another set of eyes on this to find out why it's returning a 503...

https://hub.docker.com/r/codekitchen/dinghy-http-proxy/

**Comment by markoshust** [comment]
New version out!

- Fixed bug with ./bin/magento-php getting replaced with subsequent container restarts
- Moved www-data user-specific commands and cronjob to ./bin/setupconfig
- Hard-coded WWW_DIR to /srv/www (this is a standard, shouldn't be changed...)

Updated docker-compose file at https://gist.github.com/markoshust/72d3eeadfec3746bf434ffbaa79be011 -- please test and give feedback.

This might be final release candidate before tagging these next versions as final, as long as there are no bugs anywhere.

**Comment by sadhasivam** [comment]
ahhh.. 👍  i about to reply for ```Fixed bug with ./bin/magento-php getting replaced with subsequent container restarts``` for this. thanks so much.

**Comment by markoshust** [comment]
@sadhasivam cool 🎯 

What I'm doing with the default `./bin/magento` file is moving it to `./bin/magento-php`. I then wrote a special script at `./bin/magento` that chroots to the `www-user` user, and executes `./bin/magento-php`. So.... make sure you keep running the command at `./bin/magento` (and not `./bin/magento-php`), to make sure permissions don't completely screw up when executing. 

A lot of what I'm doing is a chess game with permissions, to make sure everything always runs with the `www-user` user. I'll hold for a day or two (or five) until I can get enough people to verify everything is working with this :)

**Comment by markoshust** [comment]
This should now be fixed. New docker image tags for php image at https://github.com/mageinferno/docker-magento2-php

Somewhat but not really related to this ticket, I also pushed out an updated nginx image
https://github.com/mageinferno/docker-magento2-nginx

Also updated the docker-compose.yml file
https://github.com/mageinferno/magento2-docker-compose

**Comment by markoshust** [comment]
FYI all, just put a blog post out summarizing what happened in this ticket and the resolution
https://mageinferno.com/blog/magento-2-speed-security-permissions-docker

**Comment by gabrielqs** [comment]
@markoshust No permission errors here. Great work!

Only things i had to change were to set some environment variables so dinghy would create the correct DNS entries. Also the nginx container was not able to bind itself to the 80 port, so i had to expose the port differently. All is working fine after these small changes.

Gist for the docker-composer.yml [here](https://gist.github.com/gabrielqs/4705f25dd18009e57a7ad395ec62cd27#file-docker-compose-yml-L9), I'm on el capitan.

**Comment by michhel** [comment]
hi everyone 
i encountered these errors after deleting cache files. now the site is not opening can you please suggest me the procedure to solve these errors

> **Fatal error: Uncaught exception 'Zend_Cache_Exception' with message 'cache_dir "/home/revelidaete/public_html/var/page_cache" is not writable'** in

 /home/revelidaete/public_html/vendor/magento/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /home/revelidaete/public_html/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/hom...') #1 /home/revelidaete/public_html/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/home/revelidae...') #2 /home/revelidaete/public_html/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /home/revelidaete/public_html/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /home/revelidaete/public_html/vendor/magento/framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true) #5 /ho in /home/revelidaete/public_html/vendor/magento/zendframework1/library/Zend/Cache.php on line 209

**Comment by markoshust** [comment]
@michhel i think the error is pretty direct:
```"/home/revelidaete/public_html/var/page_cache" is not writable'```

**Comment by gflosi** [comment]
@jagwire16, @michhel

You must config the security context of the files and force it to be in the Read and Write mode.

This is the command:

`chcon -R -t httpd_sys_rw_content_t directory_or_filename`

**Comment by afnanm** [comment]
magento front end was working but now i git this error:

`Fatal error: Uncaught Zend_Cache_Exception: cache_dir "/var/www/vhosts/amimpact1972.com/httpdocs/var/cache/" is not writable in /var/www/vhosts/amimpact1972.com/httpdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /var/www/vhosts/amimpact1972.com/httpdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/var...') #1 /var/www/vhosts/amimpact1972.com/httpdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/var/www/vhosts...') #2 /var/www/vhosts/amimpact1972.com/httpdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /var/www/vhosts/amimpact1972.com/httpdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /var/www/vhosts/amimpact1972.com/httpdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(158): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Ca in /var/www/vhosts/amimpact1972.com/httpdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209`

how can i fix it? also this error for admin page

**Comment by markoshust** [comment]
Make sure your permissions are set correctly for the var folder within your
source directory, and ownerships are set correctly after your volume is
mounted.

**Comment by afnanm** [comment]
permission of var directory is 777. but how to do this:  and ownerships are set correctly after your volume is
mounted.?
