### ISSUE TITLE
Copying /var/www/html from appdata volume fails

### ISSUE THREAD

**Issue by nathanjosiah** [mageinferno/magento2-docker-compose#50]
I have followed the setup guide using the composer auth method and everything installs and runs great. My problem is that when I attempt to copy the filesystem as described in the README, I get the following:

```
C:\Users\NathanS\mage2>docker cp 81a:/var/www/html ./
symlink \var\www\.composer C:\Users\NathanS\mage2\html\var\composer_home: A required privilege is not held by the client.
```

I have tried using the command prompt as well as git-bash (Mingw64) both with the same result. I have tried many different things to bypass this issue but have had no success. I also can't find anybody else talking about this problem.

I am on 64bit Windows 10 Enterprise running as an Administrative user. 

What can I do to get this to work?

**Comment by markoshust** [comment]
Seems specific to Windows, so I'll let the community chime in here (I'm mac/linux guy).

**Comment by nathanjosiah** [comment]
Update: I just tried again on a differnt, exactly same steps/commands/setup/user/OS as the first but this time it ran without any issues.

**Comment by markoshust** [comment]
Ok it's possible the container wasn't booted 100% yet or some other system config/version specific error. Thanks for the update.

**Comment by nathanjosiah** [comment]
This isn't closed though, I still need it to work. I can't use the other machine regularly. 

I am sure the machine was booted all the way as for versions we can look at that but it seems to me that it is more likely some type of permissions issue or path mapping problem.

**Comment by markoshust** [comment]
You just said it ran without issues your second time. That tells me it's something specific to your environment. Unless you can consistently replicate this on a specific machine with predictable results, I think we should keep this one closed.

**Comment by nathanjosiah** [comment]
I said I ran in on a second computer with no issues. It is 100% consistent on my primary workstation.

**Comment by markoshust** [comment]
That's fine, but we can't just have a report here that says "didnt work". Need environment, steps to replicate, confirmation by at least a 2nd user, etc...

**Comment by nathanjosiah** [comment]
Here is a list of my version information:

Software | Version
------ | --------
Docker | 1.12.5, build 7392c3b
docker-compose | 1.9.0, build 2585387
docker-machine | 0.8.2, build e18a919
Virtualbox | 5.1.10 r112026 (Qt5.6.2)
Windows 10 | 64bit Enterprise
Boot2Docker | 1.12.5, build fc49b1e
mageinferno/magento2-nginx | 1.11-0
mageinferno/magento2-php  | 7.0-fpm-0
tianon/true | latest (f63a935f4203)
percona | 5.7

I am running as an Administrative user with full permissions for my installation folder. 

I followed the steps exactly using the composer Magento marketplace authentication method from here: https://github.com/mageinferno/magento2-docker-compose/blob/2e154f67abda9c95b1227bed6999d6c6f15f4ecf/README.md

The step that failed was when I was running the `docker cp CONTAINERID:/var/www/html ./` command. (I had replaced `CONTAINERID` with the actual container ID, of course).

If I skipped that step and proceeded, I had a successful install with everything working as it should.

**Comment by markoshust** [comment]
Are you sure the volume was not mounted to the host already when you ran this command?

**Comment by nathanjosiah** [comment]
I made a 3:38 video of my entire process. The `docker cp` is at 1:03.
https://youtu.be/HdO609BSDHE

**Comment by markoshust** [comment]
@nathanjosiah you're copying from the data volume container. copy from the php one. you can't copy from appdata because it's just a scratch volume.

**Comment by nathanjosiah** [comment]
@markoshust Following the video I provided (after `docker-compose up app`) I attempted the `docker cp` using the `phpfpm` containerand received the same error but with a different file. 

![image](https://cloud.githubusercontent.com/assets/665104/22904323/dca5d064-f1f0-11e6-9929-82fd1290936e.png)

If I attempt the command before the `docker-compose up app` the result is the same.

**Comment by pedromtalavera** [comment]
Hi @nathanjosiah.

I'm having the same issue, after installing using the composer method on a Windows machine.

Do you find a solution?

**Comment by nathanjosiah** [comment]
@pedromtalavera I only found the workaround that I described in one of my [previous comments](https://github.com/mageinferno/magento2-docker-compose/issues/50#issuecomment-277304424). If I skip the step and don't use a shared volume it runs fine. However, then I can't actually perform any development so it isn't really a viable workaround. 

@markoshust needed a second user to verify the problem before looking into it so now he has one.

**Comment by markoshust** [comment]
thanks for the update. i actually do not intend to look into this, as i don't have a windows machine.

i don't think there is an actual issue of anything specific relating to this docker image. there is nothing weird going on with these docker containers regarding filesystem permissions, so i think this would fall back to a general windows + docker issue. that said, i'll reopen this ticket for windows people to work it out as it seems it could be a fairly common problem that might hold up some devs.

here's a couple links to look into:
https://appuals.com/a-required-privilege-is-not-held-by-the-client-0x80070522/
https://github.com/moby/moby/pull/28923

this looks specific to symbolic links on windows. did you try the `docker cp` command with `-L`?
https://docs.docker.com/engine/reference/commandline/cp/#extended-description

`docker cp -L CONTAINERID:/var/www/html ./`

if that works, i'd probably suggest updating the readme. lmk!

**Comment by markoshust** [comment]
Closing to inactivity

**Comment by nathanjosiah** [comment]
Sorry for the delayed response @markoshust. I am still seeing the issue and the links did not provide any new info unfortunately. 

As a side note, trying this again from scratch using the master branch produces new issues as the README is out of sync with the docker-compose file so the instructions can't be followed exactly.

**Comment by pedromtalavera** [comment]
Hi @nathanjosiah and @markoshust  sorry for the delay.

It work for me after open a new cmd with "Run as administrator" and then running

`docker cp -L CONTAINERID:/var/www/html ./`

I hope this helps you.

**Comment by edocollado** [comment]
> Hi @nathanjosiah and @markoshust sorry for the delay.
> 
> It work for me after open a new cmd with "Run as administrator" and then running
> 
> `docker cp -L CONTAINERID:/var/www/html ./`
> 
> I hope this helps you.

thanks
