### ISSUE TITLE
Stop/Restart docker-compose returns errors

### ISSUE THREAD

**Issue by denisinla** [mageinferno/magento2-docker-compose#55]
Is there any literature for stopping containers properly. Looks like whenever running ``docker-compose down`` and ``docker-compose up -d app`` nginx returns a 404 error.

Any ideas?

**Comment by markoshust** [comment]
This isn't a bug report, so I'm closing out this ticket. `docker-compose stop` is your friend, and the docker documentation.

**Comment by nathanjosiah** [comment]
@markoshust If my computer has an improper shutdown I can't seem to find a way to get the containers to run properly. `docker-compose stop` works fine when I can run it but if I can't, is there a way to get the containers running properly again without having to start from scratch every time?

**Comment by markoshust** [comment]
I'm not sure. Might want to check stackoverflow as this doesn't sound specific to this project.
