### ISSUE TITLE
Invalid service name "php-fpm" 

### ISSUE THREAD

**Issue by danemco** [mageinferno/magento2-docker-compose#6]
When running this docker-compose.yml script with `docker-compose up`, I get this output:

    user@desktop:/home/dpurcell/dev2/magento2-docker-compose# docker-compose up
    Invalid service name "php-fpm" - only [a-zA-Z0-9] are allowed

Here's my docker-compose version:

    user@desktop:/home/dpurcell/dev2/magento2-docker-compose# docker-compose -v
    docker-compose version: 1.3.1
    CPython version: 2.7.10
    OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015

What am I doing wrong?

**Comment by markoshust** [comment]
Seems you are on an older version of docker-compose. Did you try upgrading to 1.4.x? Also make sure the name php-fpm is in double quotes in your docker-compose definition.

**Comment by danemco** [comment]
Thank you, that was it. docker-composer version 1.3 comes installed on Ubuntu Wiley.  I apt-get removed that package and installed version 1.5.2. manually from Docker's github.
