### ISSUE TITLE
Document that # volumes: *appvolumes needs to be uncommented when uncommenting the mount points for code and design

### ISSUE THREAD

**Issue by zsoerenm** [mageinferno/magento2-docker-compose#64]
Please document in the readme that # volumes: *appvolumes in docker-compose.override.yml needs to be uncommented as well when uncommenting the mount points for code and design.

**Comment by lilbumblebear** [comment]
Thanks for the tip, this resolved my issue when adding a new module in app/code and trying to run 
```
docker-compose exec phpfpm ./bin/magento module:enable Vendor_Module
```
only to get the error: 
```
Unknown module(s): 'Vendor_Module'
```

**Comment by markoshust** [comment]
all you need to do is uncomment the appropriate lines in the `docker-compose.override.yml.dist` file -- it's pretty self-explanatory
