### ISSUE TITLE
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 12288 bytes) in /var/www/html/vendor/zendframework/zend-modulemanager/src/ModuleManager.php

### ISSUE THREAD

**Issue by dnarbuzov** [mageinferno/magento2-docker-compose#66]
Hi,
I'm getting the next error after docker-compose  up.

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 12288 bytes) in /var/www/html/vendor/zendframework/zend-modulemanager/src/ModuleManager.php

Here is docker-compose code:

version: '3'
services:

    phpfpm:
        build: ./.docker/phpfpm
        links:
            - database
        volumes:
            - ./:/var/www/html
        environment:
            - XDEBUG_CONFIG=remote_host=10.200.10.1
            - PHP_IDE_CONFIF=serverName=terp

    nginx:
        build: ./.docker/nginx
        links:
            - phpfpm
        volumes:
            - .:/var/www/html
        ports:
            - "8083:80"

    database:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=qwerqwer
            - MYSQL_DATABASE=terp
            - MYSQL_USER=terp
            - MYSQL_PASSWORD=qwerqwer
        ports:
            - "3311:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql

What could be the reason of that?
Thanks.

**Comment by markoshust** [comment]
Please post questions to stackoverflow, issues are just for filing bugs related to this docker repo.
