### ISSUE TITLE
how to serve index.php file from root,not from pub folder?

### ISSUE THREAD

**Issue by sivajik34** [mageinferno/magento2-docker-compose#67]
i cloned your repo. It's working fine.but its calling root/pub/index.php not from root/index.php.
because i have issue with web setup wizard menu missing.
i have seen this line in docker-magento2-nginx/conf/default.conf.
root $MAGE_ROOT/pub;
so i want like this : root  $MAGE_ROOT.

**Comment by markoshust** [comment]
the public root should in fact be the `pub` folder. i don't think this repo is supporting any web-setup wizard, as there is a supplied setup from command line.
