### ISSUE TITLE
Setup finishes but no Magento

### ISSUE THREAD

**Issue by danemco** [mageinferno/magento2-docker-compose#7]
After running `docker-compose up`, it says it finished the installation and setup. When I hit http://localhost:80, however, I get a 404 (I verified that port 80 is forwarding to the nginx install). Here's the output:

<pre>
setup_1   | Running Magento 2 setup script...
setup_1   | Could not open input file: /src/bin/magento
setup_1   | Reindexing all indexes...
setup_1   | Could not open input file: /src/bin/magento
setup_1   | Deploying static view files...
setup_1   | Could not open input file: /src/bin/magento
setup_1   | Applying ownership & proper permissions...
setup_1   | find: `pub': No such file or directory
setup_1   | find: `pub': No such file or directory
setup_1   | find: `/src/var/generation': No such file or directory
setup_1   | The setup script has completed execution.
magento2dockercompose_setup_1 exited with code 0
app_1     | 172.17.42.1 - - [20/Jan/2016:19:52:02 +0000] "GET / HTTP/1.1" 404 168 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0" "-"
</pre>

Did I miss a step?

**Comment by markoshust** [comment]
Here's your error:
```Could not open input file: /src/bin/magento```

Ensure /src is a listed volume under appdata.

appdata:
  image: tianon/true
  volumes:
    - /src
    - ~/.composer:/root/.composer

**Comment by danemco** [comment]
I removed my src directory and started over. There must have been a problem during the first setup.

**Comment by markoshust** [comment]
Ok cool, glad you figured it out. Might have been related to the other ticket.

**Comment by danemco** [comment]
Now for a dumber question: how do I get to the admin? When I access
mysite.com/index.php, I get the Luma site (the test data). When I go to
mysite.com/admin, I get a 404 page.  Could it be that I have a module
disabled? I can't figure out how to access / ssh into the docker image to
see if I have the admin module enabled or not.

**Comment by markoshust** [comment]
No such thing as a dumb question! This is a good one.

Admin urls are now randomly generated in M2 (this is good, as it prevents brute-force hacking). You can check the file at `/src/app/etc/env.php` which will give you the admin url. You can also issue the following line:
```docker exec -it PHPCONTAINERID head -5 app/etc/env.php

This should give you the first 5 lines of app/etc/env.php, the 5th line being the admin url.

**Comment by danemco** [comment]
That worked! Thank you!
